### ISSUE TITLE
Android Application crashes when the app became paused

### ISSUE THREAD

**Issue by itcherry** [plaid/react-native-plaid-link-sdk#133]
Hi!

I'm having an issue using your SDK on Android.
I followed the installation instructions and I am using v3.2.0.

The SDK opens and everything works fine. The crash happens when the user pauses the application (go to the main menu) or when switched to another process.

*Steps to reproduce:*
1) Open Android app with react native.
2) Launch Plaid with, for example, sandbox environment.
3) Link bank account with a sandbox username and password.
4) After successful bank account link try to click on `home` button on your device/emulator
5) The crash happens with the following stacktrace:

```
Manufacturer: Google
Model: Android SDK built for x86
Brand: google
Device: generic_x86
Board: unknown
Hardware: ranchu
Product: sdk_gphone_x86
Android Version: 8.1.0

io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Failed resolution of: Lcom/plaid/r;
   io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
   io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
   io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
   java.lang.Thread.run(Thread.java:764)
Caused by:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/plaid/r;
   java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
   java.lang.reflect.Method.getParameterTypes(Method.java:179)
   java.lang.Class.getDeclaredMethods(Class.java:1881)
   java.lang.reflect.Proxy.getMethodsRecursive(Proxy.java:752)
   java.lang.reflect.Proxy.getMethods(Proxy.java:741)
   java.lang.reflect.Proxy.-wrap2(Unknown Source:0)
   java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:633)
   java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:566)
   java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
   java.lang.reflect.WeakCache.get(WeakCache.java:127)
   java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
   java.lang.reflect.Proxy.newProxyInstance(Proxy.java:820)
   retrofit2.Retrofit.create(Retrofit.java:135)
   com.plaid.f$f.invoke(SourceFile:2)
   com.plaid.f$f.invoke(SourceFile:1)
   kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
   com.plaid.f.c(Unknown Source:2)
   com.plaid.f.a(SourceFile:149)
   com.plaid.h$c.a(SourceFile:1)
   com.plaid.h$c.apply(SourceFile:1)
   io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
   com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
   io.reactivex.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:82)
   io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:53)
   io.reactivex.Observable.subscribe(Observable.java:12267)
   com.tspoon.traceur.ObservableOnAssemblyCallable.subscribeActual(ObservableOnAssemblyCallable.java:42)
   io.reactivex.Observable.subscribe(Observable.java:12267)
   io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable.subscribeActual(ObservableFlatMapCompletableCompletable.java:49)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   com.tspoon.traceur.CompletableOnAssembly.subscribeActual(CompletableOnAssembly.java:41)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   com.tspoon.traceur.CompletableOnAssembly.subscribeActual(CompletableOnAssembly.java:41)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   io.reactivex.internal.operators.completable.CompletableToSingle.subscribeActual(CompletableToSingle.java:38)
   io.reactivex.Single.subscribe(Single.java:3603)
   com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
   io.reactivex.Single.subscribe(Single.java:3603)
   io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
   io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
   io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
   io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
   java.lang.Thread.run(Thread.java:764)
Caused by:
java.lang.ClassNotFoundException: Didn't find class "com.plaid.r" on path: DexPathList[[zip file "/data/app/com.aspiration.app.alpha-xZtvFkSiPcgBvCtnZbyVLw==/base.apk"],nativeLibraryDirectories=[/data/app/com.aspiration.app.alpha-xZtvFkSiPcgBvCtnZbyVLw==/lib/x86, /data/app/com.aspiration.app.alpha-xZtvFkSiPcgBvCtnZbyVLw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
   dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
   java.lang.ClassLoader.loadClass(ClassLoader.java:379)
   java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
   java.lang.reflect.Method.getParameterTypes(Method.java:179)
   java.lang.Class.getDeclaredMethods(Class.java:1881)
   java.lang.reflect.Proxy.getMethodsRecursive(Proxy.java:752)
   java.lang.reflect.Proxy.getMethods(Proxy.java:741)
   java.lang.reflect.Proxy.-wrap2(Unknown Source:0)
   java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:633)
   java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:566)
   java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
   java.lang.reflect.WeakCache.get(WeakCache.java:127)
   java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
   java.lang.reflect.Proxy.newProxyInstance(Proxy.java:820)
   retrofit2.Retrofit.create(Retrofit.java:135)
   com.plaid.f$f.invoke(SourceFile:2)
   com.plaid.f$f.invoke(SourceFile:1)
   kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
   com.plaid.f.c(Unknown Source:2)
   com.plaid.f.a(SourceFile:149)
   com.plaid.h$c.a(SourceFile:1)
   com.plaid.h$c.apply(SourceFile:1)
   io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
   com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
   io.reactivex.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:82)
   io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:53)
   io.reactivex.Observable.subscribe(Observable.java:12267)
   com.tspoon.traceur.ObservableOnAssemblyCallable.subscribeActual(ObservableOnAssemblyCallable.java:42)
   io.reactivex.Observable.subscribe(Observable.java:12267)
   io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable.subscribeActual(ObservableFlatMapCompletableCompletable.java:49)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   com.tspoon.traceur.CompletableOnAssembly.subscribeActual(CompletableOnAssembly.java:41)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   com.tspoon.traceur.CompletableOnAssembly.subscribeActual(CompletableOnAssembly.java:41)
   io.reactivex.Completable.subscribe(Completable.java:2309)
   io.reactivex.internal.operators.completable.CompletableToSingle.subscribeActual(CompletableToSingle.java:38)
   io.reactivex.Single.subscribe(Single.java:3603)
   com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
   io.reactivex.Single.subscribe(Single.java:3603)
   io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
   io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
   io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
   io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
   java.lang.Thread.run(Thread.java:764)
```
Take a look at `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/plaid/r;` message there. Proguard is not cutting classes, cause minify and shrink resources are disabled.

Maybe something wrong with Plaid or React Native setup on Androidd side.
I would appreciate all your help!

**Comment by itcherry** [comment]
Btw, Android SDK library version is `1.4.1`

**Comment by itcherry** [comment]
The important thing that we are not using monorepo, but different repositories for Android, iOS and react native code instead. Maybe it can help somehow to detect this bug. 

Also, now it is crashing just when opening Plaid screen with the same crash report:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/plaid/r;
        at com.plaid.s5.a(SourceFile:22)
        at com.plaid.s5.b(SourceFile:2)
        at com.plaid.o1$b.a(SourceFile:20)
        at com.plaid.x1.get(SourceFile:2)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.plaid.m1.b(SourceFile:1)
        at com.plaid.x2.a(SourceFile:14)
        at com.plaid.m9.<init>(SourceFile:15)
        at com.plaid.r9.<init>(SourceFile:1)
        at com.plaid.o3.<init>(SourceFile:1)
        at com.plaid.e3.a(SourceFile:16)
        at com.plaid.link.internal.LinkActivity.a(SourceFile:5)
        at com.plaid.link.internal.LinkActivity.a(SourceFile:2)
        at com.plaid.z9.j(SourceFile:2)
        at com.plaid.link.internal.LinkActivity.j(SourceFile:1)
        at com.plaid.v9.onActivityCreated(SourceFile:11)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at com.plaid.x9.onStart(SourceFile:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7347)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3116)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plaid.r" on path: DexPathList[[zip file "/data/app/com.aspiration.app.alpha-r213nixMr1NbS9XD2fgg8w==/base.apk"],nativeLibraryDirectories=[/data/app/com.aspiration.app.alpha-r213nixMr1NbS9XD2fgg8w==/lib/arm64, /data/app/com.aspiration.app.alpha-r213nixMr1NbS9XD2fgg8w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by amytang0** [comment]
Hi, would you mind sharing your OKHTTP3 dependencies?

**Comment by itcherry** [comment]
@amytang0 We are using following dependencies:
```
implementation "com.squareup.okhttp3:okhttp:4.2.2"
implementation "com.squareup.okhttp3:logging-interceptor:4.2.2"
```

**Comment by amytang0** [comment]
Hi, we are working on a more flexible solution, but would it be possible to use:
```
implementation "com.squareup.okhttp3:okhttp:4.6.0"
implementation  "com.squareup.okhttp3:logging-interceptor:4.6.0"
```
for now?

**Comment by itcherry** [comment]
It is still crashing with `4.6.0`. `4.7.2` version has the same. Btw, for release builds (with `minifyEnabled`) it works much more stable

**Comment by amytang0** [comment]
Hi sorry for the delayed response. 2.0 (which is coming out approximately next Monday)  should fix this issue.

**Comment by amytang0** [comment]
Closing this issue after 30 days
