### ISSUE TITLE
Android App crash

### ISSUE THREAD

**Issue by pira22** [plaid/react-native-plaid-link-sdk#145]
Hi!
I'm facing an issue once i launch plaid with the latest SDK.
this is the stacktrace.
```io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:126)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:171)
        at androidx.work.WorkManager.initialize(WorkManager.java:204)
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6835)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6382)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6286)
        at android.app.ActivityThread.access$1200(ActivityThread.java:241)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7156) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: java.lang.ClassNotFoundException: androidx.work.impl.utils.futures.AbstractFuture
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:171) 
        at androidx.work.WorkManager.initialize(WorkManager.java:204) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6835) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6382) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6286) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:241) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7156) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/ListenableFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:171) 
        at androidx.work.WorkManager.initialize(WorkManager.java:204) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6835) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6382) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6286) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:241) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7156) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.ListenableFuture" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.haulpay_mobile-Y21ttP7ubhiAG82BSGFiQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.haulpay_mobile-Y21ttP7ubhiAG82BSGFiQQ==/lib/arm, /data/app/com.haulpay_mobile-Y21ttP7ubhiAG82BSGFiQQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:171) 
        at androidx.work.WorkManager.initialize(WorkManager.java:204) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6835) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6382) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6286) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:241) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7156) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
```

**Comment by pira22** [comment]
just resolve it by removing this `implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
