### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by alexjbartlett** [plaid/react-native-plaid-link-sdk#146]
Hi

After adding react-native-plaid-link-sdk version 4.0.1 and following the android setup instructions our android app crashes as soon as the sdk is imported.  Stack trace below.

react-native-plaid-link-sdk version 4.0.1 
com.plaid.link:sdk-core version 2.0.0

```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.upside, PID: 17290
java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.upside-Y8m0Gn7THobTZ06zSX9gSA==/base.apk!classes3.dex)
	at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.java:91)
	at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:74)
	at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by zsweigart** [comment]
Hi @alexjbartlett thanks for the report.  After some investigation we've seen that the core Facebook React Native library specifies an exact dependency for `com.squareup.okhttp3:okhttp-urlconnection:3.12.1`.  See the Facebook React Native library [here](https://github.com/facebook/react-native/blob/v0.63.0-rc.1/ReactAndroid/gradle.properties).

Our React Native sdk is a wrapper around our native android sdk which requires `com.squareup.okhttp3:okhttp-urlconnection:4.+` so it transitively depends on version `4.+`. 

A work around is to add 
```
implementation "com.squareup.okhttp3:okhttp-urlconnection:4.+"
```
To your app level build.gradle file (right below the `implementation 'com.plaid.link:sdk-core:2.0.0'` line).

We will look into a long term solution but for now this should work.

**Comment by zsweigart** [comment]
This issue appears to be the same as #74
