### ISSUE TITLE
Android Build failed: java.lang.RuntimeException: Duplicate class androidx.appcompat.content.res.AppCompatResources

### ISSUE THREAD

**Issue by phliem** [plaid/react-native-plaid-link-sdk#153]
I am trying to upgrade from '3.0.1' to '4.0.1' and not sure what I am doing wrong, but keep on getting those build error. any help would be massively appreciated. Thanks

Fyi I am using

```    
    implementation 'com.plaid.link:sdk-core:1.0.0'
    implementation 'com.squareup.okhttp3:okhttp:4.2.1' 
    implementation 'com.squareup.okhttp3:logging-interceptor:4.2.1'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.2.1'
```

Here are the logs if that help
```
> Task :app:checkDevDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
609 actionable tasks: 3 executed, 606 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class androidx.appcompat.content.res.AppCompatResources found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.content.res.AppCompatResources$ColorStateListCacheEntry found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$1 found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimatableTransition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimatedStateListState found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimatedVectorDrawableTransition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimationDrawableTransition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$FrameInterpolator found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$Transition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer$1 found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer$BlockInvalidateCallback found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer$DrawableContainerState found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableWrapper found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.StateListDrawable found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.StateListDrawable$StateListState found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.DrawableUtils found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.ResourcesWrapper found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.TintContextWrapper found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.TintInfo found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.TintResources found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.VectorEnabledTintResources found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class androidx.appcompat.content.res.AppCompatResources found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.content.res.AppCompatResources$ColorStateListCacheEntry found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$1 found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimatableTransition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimatedStateListState found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimatedVectorDrawableTransition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$AnimationDrawableTransition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$FrameInterpolator found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.AnimatedStateListDrawableCompat$Transition found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer$1 found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer$BlockInvalidateCallback found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableContainer$DrawableContainerState found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableWrapper found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.StateListDrawable found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.graphics.drawable.StateListDrawable$StateListState found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.DrawableUtils found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.ResourcesWrapper found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.TintContextWrapper found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.TintInfo found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.TintResources found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  Duplicate class androidx.appcompat.widget.VectorEnabledTintResources found in modules classes.jar (androidx.appcompat:appcompat-resources:1.1.0) and classes.jar (androidx.appcompat:appcompat:1.0.0)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at runOnAllDevices (/Users/liem/Desktop/repos/emma-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/liem/Desktop/repos/emma-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /Users/liem/Desktop/repos/emma-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/liem/Desktop/repos/emma-app/node_modules/@react-native-community/cli/build/index.js:164:9)
```

**Comment by JeroenMols** [comment]
Hi @phliem ,

I'm currently not yet able to reproduce your issue. Could you try updating the Android SDK to 2.0.0?
```
implementation 'com.plaid.link:sdk-core:1.0.0'
```

If that doesn't help, can you share the output of `./gradlew :app:dependencies`? (ran from your `android` folder)

Thank you,
Jeroen

**Comment by phliem** [comment]
Hi Jeroen

Thanks for your help. I tried to update to 'com.plaid.link:sdk-core:2.0.0' but had the same error. 

Here is the output you requested
https://gist.github.com/phliem/c641c82170259480fd57f553915f32ae

Thanks
Liem

**Comment by JeroenMols** [comment]
In your `android/app/build.gradle` file, can you try replacing:

```
    implementation project(':react-native-plaid-link-sdk')
```

with

```
    implementation(project(':react-native-plaid-link-sdk')) {
        exclude group: 'androidx.appcompat', module: 'appcompat-resources'
    }
```

**Comment by phliem** [comment]
Just tried and I am getting the same error. If that help here are all dependencies in `build.gradle`

```
dependencies {
    implementation 'im.crisp:crisp-sdk:0.1.6'
    implementation 'com.android.installreferrer:installreferrer:1.1'
    implementation 'com.google.firebase:firebase-dynamic-links:19.0.0'
    implementation ("com.google.android.gms:play-services-base:16.1.0"){ force = true }
    implementation ("com.google.android.gms:play-services-location:16.0.0"){ force = true }
    implementation 'com.datatheorem.android.trustkit:trustkit:1.1.2'
    implementation 'com.facebook.fresco:fresco:1.13.0'
    implementation 'com.facebook.fresco:animated-gif:1.13.0'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation(project(':react-native-plaid-link-sdk')) {
        exclude group: 'androidx.appcompat', module: 'appcompat-resources'
    }
    implementation 'com.plaid.link:sdk-core:2.0.0' // Plaid Sdk
    implementation 'com.squareup.okhttp3:okhttp:4.2.1' // Plaid Sdk
    implementation 'com.squareup.okhttp3:logging-interceptor:4.2.1' // Plaid Sdk
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.2.1' // Plaid Sdk
    configurations.all {
        resolutionStrategy {
            force 'com.android.support:support-v4:27.1.0'
            force 'com.android.support:appcompat-v7:27.1.1'
        }
    }
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}
```

**Comment by phliem** [comment]
I just found the problem it was coming from the `resolutionStrategy`
`force 'com.android.support:appcompat-v7:27.1.1'`
Once I remove that it is compiling as expected.

Thanks for your help!

**Comment by JeroenMols** [comment]
I was just looking into something similar... It seems as if you're still using the legacy `android support libraries` instead of the newer `androidx libraries`. Normally the Android Gradle plugin would use a tool called `jettifier` to convert the old libraries to the new ones during build. Maybe that's causing a duplicate dependency on your path... 🤔 

More info about that here: https://developer.android.com/jetpack/androidx/migrate

I'm still confused as to how this was causing the issue in your place, but I'm very happy you were able to figure things out. Great job! 🙏

**Comment by luke-knol** [comment]
I am running into this same error but my resolution strategy does only contains a single config:    `force 'androidx.annotation:annotation:1.0.0'` commenting out does not yield any different results.

When i run `./gradlew :app:dependencies` i get the follow error:
```
* Where:
Build file '/Users/lukeknol/src/glsc/shopwithscrip.client/node_modules/react-native-plaid-link-sdk/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':react-native-plaid-link-sdk'.
> Cannot change dependencies of configuration ':react-native-plaid-link-sdk:classpath' after it has been resolved
```
@JeroenMols any suggestions?  I have also tried:

> implementation(project(':react-native-plaid-link-sdk')) {
>     exclude group: 'androidx.appcompat', module: 'appcompat-resources'
> }
