### ISSUE TITLE
Android crash:  java.lang.IllegalStateException

### ISSUE THREAD

**Issue by phliem** [plaid/react-native-plaid-link-sdk#164]
Hi

I am trying to upgrade from plaid 3.0.1 to 4.0.1 and getting crashes on android only. It works as expected on iOS with 4.0.1. With the 3.0.1 both iOS and Android works. I also tried 3.3.2 but getting the same crash.

Thanks for your help!

**My config:**
RN: 0.61.5
react-native-plaid-link-sdk: 4.0.1
implementation project(':react-native-plaid-link-sdk')
implementation 'com.plaid.link:sdk-core:2.0.0'
implementation "com.squareup.okhttp3:okhttp:4.2.1"
implementation "com.squareup.okhttp3:logging-interceptor:4.2.1"
implementation "com.squareup.okhttp3:okhttp-urlconnection:4.2.1"

**If that helps here is the log of my devices**
```
07-24 18:02:10.404  1962  2091 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@eb1e4bc)
07-24 18:02:10.405  1962  1977 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@eb1e4bc)
07-24 18:02:11.158  1962  3505 I ActivityManager: START u0 {flg=0x4000000 cmp=com.emmaprod/com.plaid.link.internal.LinkActivity} from uid 10085
07-24 18:02:11.160  1962  2805 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE
07-24 18:02:11.160  1962  2805 D PackageManager: Clear ephemeral installer activity
07-24 18:02:11.218 15763 15763 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@e4d7829
07-24 18:02:11.304  1648  1703 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3641344
07-24 18:02:11.309  1648  3193 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3641344
07-24 18:02:11.316  1648  1703 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3641344
07-24 18:02:11.325  2942  2942 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
07-24 18:02:11.326  2942  2942 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound
07-24 18:02:11.332 15763 15877 D EGL_emulation: eglMakeCurrent: 0xe3157100: ver 3 0 (tinfo 0xdcff15f0)
07-24 18:02:11.346 15763 15843 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=49cf4ff5-71a0-499e-a874-8d3d10e2e91c, tags={ com.plaid.core.analytics.batch.AnalyticsBatchUploadWorker } ]
07-24 18:02:11.348  1962  1986 I ActivityManager: Displayed com.emmaprod/com.plaid.link.internal.LinkActivity: +142ms
07-24 18:02:11.350  2138  2405 D EGL_emulation: eglMakeCurrent: 0xc86d14e0: ver 3 0 (tinfo 0xdafa05b0)
07-24 18:02:11.358  1962  2805 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE
07-24 18:02:11.358  1962  2805 D PackageManager: Clear ephemeral installer activity
07-24 18:02:11.408  1962  2091 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@5d931a2)
07-24 18:02:11.410  1787  1787 D SurfaceFlinger: duplicate layer name: changing Surface(name=AppWindowToken{e90f0cb token=Token{563ff9a ActivityRecord{ad7dc45 u0 com.emmaprod/com.plaid.link.internal.LinkActivity t61}}})/@0xdb45331 - animation-leash to Surface(name=AppWindowToken{e90f0cb token=Token{563ff9a ActivityRecord{ad7dc45 u0 com.emmaprod/com.plaid.link.internal.LinkActivity t61}}})/@0xdb45331 - animation-leash#1
07-24 18:02:11.413  1962  1977 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@5d931a2)
07-24 18:02:11.414  1787  1787 D SurfaceFlinger: duplicate layer name: changing Surface(name=AppWindowToken{791092a token=Token{773d215 ActivityRecord{380e5ff u0 com.emmaprod/.MainActivity t61}}})/@0x86e17ad - animation-leash to Surface(name=AppWindowToken{791092a token=Token{773d215 ActivityRecord{380e5ff u0 com.emmaprod/.MainActivity t61}}})/@0x86e17ad - animation-leash#1
07-24 18:02:11.419 15763 15763 E t4$d    : java.lang.IllegalStateException: 
07-24 18:02:11.419 15763 15763 E t4$d    : 	at com.plaid.internal.t4$f.accept(SourceFile:16)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onSuccess(SingleDoOnEvent.java:55)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at android.os.Handler.handleCallback(Handler.java:873)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at android.os.Looper.loop(Looper.java:193)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at android.app.ActivityThread.main(ActivityThread.java:6669)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at java.lang.reflect.Method.invoke(Native Method)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-24 18:02:11.419 15763 15763 E t4$d    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-24 18:02:11.419 15763 15763 E t4$d    : 
07-24 18:02:11.430  1962  1978 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
07-24 18:02:11.431  1962  1978 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
07-24 18:02:11.435  1962  3505 W ActivityManager: Duplicate finish request for ActivityRecord{ad7dc45 u0 com.emmaprod/com.plaid.link.internal.LinkActivity t61 f}
07-24 18:02:11.454  2942  2942 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
07-24 18:02:11.454  2942  2942 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound
07-24 18:02:11.464 15763 15877 D EGL_emulation: eglMakeCurrent: 0xe3157100: ver 3 0 (tinfo 0xdcff15f0)
07-24 18:02:11.556  1962  6572 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE
07-24 18:02:11.556  1962  6572 D PackageManager: Clear ephemeral installer activity
07-24 18:02:11.860  1787  1859 W SurfaceFlinger: Attempting to set client state on removed layer: com.emmaprod/com.plaid.link.internal.LinkActivity#0
07-24 18:02:11.860  1787  1859 W SurfaceFlinger: Attempting to destroy on removed layer: com.emmaprod/com.plaid.link.internal.LinkActivity#0
07-24 18:02:12.089 15763 15843 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=2e72f669-f06b-482d-8b27-5e1e52121f8b, tags={ com.plaid.core.analytics.batch.AnalyticsBatchUploadWorker } ]
07-24 18:02:12.097  1962  2805 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE
07-24 18:02:12.097  1962  2805 D PackageManager: Clear ephemeral installer activity
```

**Comment by JeroenMols** [comment]
Hi @phliem ,

Thanks for reporting your issue, could you please provide some more information for us to debug?

- Steps to reproduce
- Does this only happen after an application upgrade from 3.0.1 to 4.0.1 or also after removing the app and reinstalling?
- A longer logcat excerpt (this one doesn't show the message of the exception for instance)
- Is this reproducible on Plaid SDK 5.0.0 and Android SDK 2.1.2?

Thank you,
Jeroen

**Comment by phliem** [comment]
Hi Jeroen,

In the end, I managed to fix the crashes. Just adding some details here in case someone else encounters the error.

The crashes happened on 3.1.2, 3.3.2, 4.0.1 on android only
But before on 3.0.1 everything works as expected.

Reinstalling the app doesn't change anything. As soon as the package is upgraded to a version after 3.0.1 I will have the crashes every times.

I manage to add some more logs and figure out that before the crashes I had the following logs
```
error_code: "INVALID_FIELD"
error_message: "Android package name must be configured in the developer dashboard. See https://plaid.com/docs/link/android/#register-app-id"
error_type: "INVALID_REQUEST"
```

Which we solve by registering the app again as described in the Readme:
```
1. Register your app id
Log into your Plaid Dashboard at the API page
Next to Allowed Android package names click "Configure" then "Add New Android Package Name"
Enter your package name, for example com.plaid.example
Click "Save Changes", you may be prompted to re-enter your password
```

Thanks for your help thought
