### ISSUE TITLE
Android crashes with `java.lang.IllegalStateException`

### ISSUE THREAD

**Issue by southerneer** [plaid/react-native-plaid-link-sdk#171]
Hi, after setting up the Android integration per the docs I'm seeing crashes on Android as soon as I try to connect to Plaid. I made sure that my Android package names are registered in the dev console (as mentioned in https://github.com/plaid/react-native-plaid-link-sdk/issues/164). Compatibility-wise I'm using the recommendations on the chart in the [pending PR](https://github.com/plaid/react-native-plaid-link-sdk/pull/170/files).

```
"react-native-plaid-link-sdk": "^5.0.0"
implementation 'com.plaid.link:sdk-core:2.2.0'
```

The error message I'm seeing when connecting to Plaid:

```
2020-08-24 15:44:19.685 20834-20834/com.<redacted>.develop E/s4$d: java.lang.IllegalStateException: 
        at com.plaid.internal.s4$f.accept(SourceFile:16)
        at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onSuccess(SingleDoOnEvent.java:55)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Other relevant details:

- React Native version 0.60.5
- Tested with Android Pixel 3 emulator and Pixel 2 test device

**Comment by amytang0** [comment]
Hi, is the crashing occurring when you initially open Plaid or when you are receiving a successful result (i.e. user connected to their bank)?

**Comment by southerneer** [comment]
Hi Amy, it crashes initially when opening Plaid

**Comment by amytang0** [comment]
A couple of preliminary diagnostics: 
Can you post the configuration you're using (with your actual `public_key` replaced with {placeholder_key})?
Can you also verify that you've whitelisted your package name on the developer dashboard?

Thank you! 
Amy

**Comment by JeroenMols** [comment]
We haven't heard back from you in a month, so we're assuming you've already found a solution.
Please don't hesitate to open another issue should that not be the case. Thank you.
