### ISSUE TITLE
Application crash after added plaid configuration in android

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#28]
Application crash after added plaid configuration in android also not working any web api or http request

Please checked logcat logs
`2019-12-24 19:52:33.861 17709-17890/com.anchorusd E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.anchorusd, PID: 17709
    java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.anchorusd-S6BdJ2myTkrCxkc8Tmdafg==/base.apk:classes23.dex)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.java:91)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:74)
        at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:43)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:75)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by osikes** [comment]
@kanji-keraliya I added the following to my app build.gradle, and resolved issue    
```
    compile "com.squareup.okhttp3:okhttp:4.2.1"
    compile "com.squareup.okhttp3:logging-interceptor:4.2.1"
    compile "com.squareup.okhttp3:okhttp-urlconnection:4.2.1"
```

**Comment by zsweigart** [comment]
I am not able to reproduce with 2.0.4 and com.plaid.link:sdk-core:0.3.0.

I did not have to add any of the okhttp in my build.gradle file.  Do you have any more information on your gradle file?

**Comment by kanji-keraliya** [comment]
@osikes its work for me, Thanks

**Comment by osikes** [comment]
Cool, @zsweigart , I don't know if there is another dependency that solves this, but those additions to build.gradle have certainly been necessary for two of my projects to work with this repo. 🤷‍♂

**Comment by zsweigart** [comment]
We have updated to version 3.0 and updated the api.  You should not need those extra dependencies now.

**Comment by ShaharyarMaroof** [comment]
@zsweigart I am using the latest version of the library and I am also getting an exception running the project on Android. I shared the stacktrace [here](https://github.com/plaid/react-native-plaid-link-sdk/issues/74) as I did not find any issues logged previously.

I added the lines mentioned by @osikes and the app does not crash now.
```"react-native version": 0.60.6```
```"react-native-plaid-link-sdk": "^3.0.1"```
