### ISSUE TITLE
Android crash - Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by makx** [plaid/react-native-plaid-link-sdk#37]
This error is thrown when i sign in using react-native-google-signin. The thing is that the error happens on 
`com.plaid.PlaidModule.onActivityResult(PlaidModule.kt:222)` 
     ...
      if (data.extras != null) {
       result.putMap(DATA, Arguments.makeNativeMap(data.extras))  // <--- ??????
      }
     ...
it looks that there is something weird around this line of code and i don't understand the purpose of this line. 

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eltonai, PID: 12251
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=-1, data=Intent { (has extras) }} to activity {com.eltonai/com.eltonai.MainActivity}: java.lang.IllegalArgumentException: Could not convert class com.google.android.gms.auth.api.signin.GoogleSignInAccount
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Could not convert class com.google.android.gms.auth.api.signin.GoogleSignInAccount
        at com.facebook.react.bridge.Arguments.addEntry(Arguments.java:117)
        at com.facebook.react.bridge.Arguments.makeNativeMap(Arguments.java:147)
        at com.plaid.PlaidModule.onActivityResult(PlaidModule.kt:222)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:277)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:704)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:129)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)`

**Comment by zsweigart** [comment]
Hi @makx what version of the sdk are you using?  We just released version 3.0

**Comment by makx** [comment]
@zsweigart i'm using the 2.0.1.

**Comment by zsweigart** [comment]
Can you upgrade to 3.0?

**Comment by vafada** [comment]
This is also happening when logging in via facebook

**Comment by mscott-nimbly** [comment]
This is also happening when using Braintree payments and Plaid sdk version 3.0.1

**Comment by ShaharyarMaroof** [comment]
I am also facing the same issue with Braintree payments and Plaid SDK on 3.0.1

**Comment by ShaharyarMaroof** [comment]
hey @makx did you manage to solve this issue?

**Comment by makx** [comment]
not yet

**Comment by realabbas** [comment]
Hey I am facing this too. Any update? how to solve this

**Comment by makx** [comment]
i can't tell you if it is solved. i left the project and i couldn't figure out this.
