### ISSUE TITLE
Android Crash related to com.plaid.link.StorybookRedirectActivity

### ISSUE THREAD

**Issue by dnvarun** [plaid/react-native-plaid-link-sdk#401]
# The problem

We are seeing some crashes from our android users related to com.plaid.link.StorybookRedirectActivity. Pasted the full stack trace below

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.6                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             | yes                |
| Android OS Version                    | 9                |
| Android Devices/Emulators    | Pixel 3                |
| Occurs on iOS     | N/A                |
| iOS Version           | N/A                |
| iOS Devices/Emulators               | N/A                |

# Steps to Reproduce

Crash happening immediately on startup

# Expected Result
No crash

# Screenshots
N/A

# Logs
```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.flyfinapp/com.plaid.link.StorybookRedirectActivity}: java.lang.ClassNotFoundException: Didn't find class "com.plaid.link.StorybookRedirectActivity" on path: DexPathList[[zip file "/data/app/com.flyfinapp-VDh84eTyivgNV_LHNY-OdA==/base.apk"],nativeLibraryDirectories=[/data/app/com.flyfinapp-VDh84eTyivgNV_LHNY-OdA==/lib/arm64, /data/app/com.flyfinapp-VDh84eTyivgNV_LHNY-OdA==/base.apk!/lib/arm64-v8a, /system/lib64]]
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2881)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Caused by java.lang.ClassNotFoundException: Didn't find class "com.plaid.link.StorybookRedirectActivity" on path: DexPathList[[zip file "/data/app/com.flyfinapp-VDh84eTyivgNV_LHNY-OdA==/base.apk"],nativeLibraryDirectories=[/data/app/com.flyfinapp-VDh84eTyivgNV_LHNY-OdA==/lib/arm64, /data/app/com.flyfinapp-VDh84eTyivgNV_LHNY-OdA==/base.apk!/lib/arm64-v8a, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
       at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2869)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

# Code To Reproduce Issue 
N/A

**Comment by amytang0** [comment]
Hi, can you try to add this to your `android/app/build.gradle` and see if it resolves the issue? Thank you!
```
implementation("com.plaid.link:sdk-core:3.4.1") {
    force true
}
```

**Comment by dnvarun** [comment]
Sorry for the delayed reply on this but few more users started facing this issue. I can try the above solution but would that have any unintentional of side effects ?
