### ISSUE TITLE
New Android Crash related to com.plaid.link.StorybookRedirectActivity

### ISSUE THREAD

**Issue by dnvarun** [plaid/react-native-plaid-link-sdk#415]
# The problem

This issue was already raised here: https://github.com/plaid/react-native-plaid-link-sdk/issues/401 . But it was closed due to inactivity and I cannot reopen it right now. So creating another issue. I tried the solution mentioned in the above issue, but the app keeps crashing if I do that.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.6                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             | yes                |
| Android OS Version                    | 10                |
| Android Devices/Emulators    | Pixel 4                |
| Occurs on iOS     | N/A                |
| iOS Version           | N/A                |
| iOS Devices/Emulators               | N/A                |

# Steps to Reproduce
Crash happening immediately on startup

# Expected Result
No crash

# Screenshots
N/A

# Logs
The original crash logs are present in the above issue. The following logs are for the crash happening when I force `com.plaid.link:sdk-core:3.4.1` . I dont think this is related to exactly Plaid but this error happens only when I force 3.4.1 sdk-core

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)
       at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:52)
       at com.facebook.react.modules.network.OkHttpClientProvider.getOkHttpClient(OkHttpClientProvider.java:43)
       at com.ReactNativeBlobUtil.ReactNativeBlobUtil.<init>(ReactNativeBlobUtil.java:61)
       at com.ReactNativeBlobUtil.ReactNativeBlobUtilPackage.createNativeModules(ReactNativeBlobUtilPackage.java:19)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalStateException: Expected Android API level 21+ but was 30
       at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
       at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
       at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
       at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)
       at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:52)
       at com.facebook.react.modules.network.OkHttpClientProvider.getOkHttpClient(OkHttpClientProvider.java:43)
       at com.ReactNativeBlobUtil.ReactNativeBlobUtil.<init>(ReactNativeBlobUtil.java:61)
       at com.ReactNativeBlobUtil.ReactNativeBlobUtilPackage.createNativeModules(ReactNativeBlobUtilPackage.java:19)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
       at java.lang.Thread.run(Thread.java:923)
```

# Code To Reproduce Issue 
N/A

**Comment by amytang0** [comment]
Hi instead of forcing to 3.4.1, can you force to 3.6.0? Thank you!
