### ISSUE TITLE
Crasher

### ISSUE THREAD

**Issue by scheng-anchor** [plaid/react-native-plaid-link-sdk#657]
# The problem

it crashed the app when I tried to open the plaid link in my react native app

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | 11.8.0                                                                 |
| ReactNative Version               | 0.74.0                                                                 |
| Occurs on Android                  | yes                                                                     |
| Android OS Version                 | 14 (API Level 34)                                                         |
| Android Devices/Emulators    | e.g. Pixel 6                                              |
| Occurs on iOS                          | e.g. no                                                                     |

# Logs
```
Work [ id=2afac96c-82c4-4dac-a494-3e7bcaef145d, tags={ com.plaid.internal.core.crashreporting.internal.CrashUploadWorker } ] failed because it threw an exception/error
                                                                                                    java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                                                                                                    	at androidx.work.impl.utils.futures.a.i(SourceFile:21)
                                                                                                    	at androidx.work.impl.utils.futures.a.get(SourceFile:48)
                                                                                                    	at d0.k$b.run(SourceFile:5)
                                                                                                    	at l0.k$a.run(SourceFile:3)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                                                                                                    	at retrofit2.n.f(SourceFile:21)
                                                                                                    	at retrofit2.H.b(SourceFile:20)
                                                                                                    	at retrofit2.G.c(SourceFile:25)
                                                                                                    	at retrofit2.G$a.invoke(SourceFile:38)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy3.a(Unknown Source)
                                                                                                    	at com.plaid.internal.oh$c$a.invokeSuspend(SourceFile:74)
                                                                                                    	at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:12)
                                                                                                    	at a7.Q.run(SourceFile:129)
                                                                                                    	at f7.m$a.run(SourceFile:4)
                                                                                                    	at h7.k.run(SourceFile:3)
                                                                                                    	at h7.a.j0(SourceFile:1)
                                                                                                    	at h7.a$c.d(SourceFile:15)
                                                                                                    	at h7.a$c.p(SourceFile:29)
                                                                                                    	at h7.a$c.run(SourceFile:1)
                                                                                                    	Suppressed: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                                                                                                    		... 15 more
```

**Comment by dtroupe-plaid** [comment]
Please provide all the information requested in the template and I will reopen this issue.
